name: Train Custom TTS Model (Final Attempt)

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install System Dependencies
      run: sudo apt-get update && sudo apt-get install -y espeak-ng ffmpeg

    - name: Install Exact Python Dependencies
      run: pip install -r requirements.txt

    - name: Run Training Script
      env:
        COQUI_TOS_AGREED: 1
      run: python train_tts.py

    - name: Upload Trained Model
      uses: actions/upload-artifact@v4
      with:
        name: trained-tts-model
        path: trained_model_output/
